team_map = {
    "ARI": "Arizona Cardinals",
    "ATL": "Atlanta Falcons",
    "BAL": "Baltimore Ravens",
    "BUF": "Buffalo Bills",
    "CAR": "Carolina Panthers",
    "CHI": "Chicago Bears",
    "CIN": "Cincinnati Bengals",
    "CLE": "Cleveland Browns",
    "DAL": "Dallas Cowboys",
    "DEN": "Denver Broncos",
    "DET": "Detroit Lions",
    "GB": "Green Bay Packers",
    "HOU": "Houston Texans",
    "IND": "Indianapolis Colts",
    "JAX": "Jacksonville Jaguars",
    "KC": "Kansas City Chiefs",
    "LV": "Las Vegas Raiders",
    "LAC": "Los Angeles Chargers",
    "LAR": "Los Angeles Rams",
    "MIA": "Miami Dolphins",
    "MIN": "Minnesota Vikings",
    "NE": "New England Patriots",
    "NO": "New Orleans Saints",
    "NYG": "New York Giants",
    "NYJ": "New York Jets",
    "PHI": "Philadelphia Eagles",
    "PIT": "Pittsburgh Steelers",
    "SF": "San Francisco 49ers",
    "SEA": "Seattle Seahawks",
    "TB": "Tampa Bay Buccaneers",
    "TEN": "Tennessee Titans",
    "WSH": "Washington Commanders",
    "": "",
}


position_markets_map = {
    "QB": [
        "player_pass_completions",
        "player_pass_interceptions",
        "player_pass_tds",
        "player_pass_yds",
        "player_rush_tds",
        "player_rush_yds",
        "player_anytime_td",
    ],
    "RB": [
        "player_rush_tds",
        "player_rush_yds",
        "player_receptions",
        "player_reception_tds",
        "player_reception_yds",
        "player_anytime_td",
    ],
    "WR": [
        "player_receptions",
        "player_reception_tds",
        "player_reception_yds",
        "player_rush_tds",
        "player_rush_yds",
        "player_anytime_td",
    ],
    "TE": [
        "player_receptions",
        "player_reception_tds",
        "player_reception_yds",
        "player_anytime_td",
    ],
    "K": [
        "player_field_goals",
        "player_kicking_points",
        "player_pats",
    ],
    "D/ST": [
        "player_sacks",
        "player_defensive_interceptions",
        "player_tds_over",
    ],
}
